### PR TITLE
Add atrium preprocessing

### PR DESCRIPTION
**Pull request by hkjeldsberg**
- Added flag for meshing atrium models
- Changed main pre-processing dependency to morphMan
- Added option to vary flow extension length
- Added constant edge-length meshing method
- Remove unused files after complete pre-processing
- Updated Artery.py to reflect changes in pre-processing script

### CODE REVIEW

**Comment by ehsannkh** [comment]
Line 70 of automatedPreProcessing.py, 
     if not is_surface_capped(surface) and smoothing_method != "voronoi" 
does not work properly, it passes for both capped and clipped surfaces. 
Since is_surface_capped(surface) function in morphman surface_operation.py returen return a tuple with 2 indices, and the first index is boolean, maybe that line can be modified as 
     if is_surface_capped(surface)[0] and smoothing_method != "voronoi":

**Comment by ehsannkh** [comment]
Maybe it would be a good idea to give the option for adding different extension lengths at inlet and outlet?

**Comment by ehsannkh** [comment]
Maybe some comments about how to select the numbers for input arguments of get_uncapped_surface function
surface = get_uncapped_surface(surface, gradients_limit=0.01, area_limit=20, circleness_limit=5)

**Comment by ehsannkh** [comment]
The previous atrium_present flag has changed to is_atrium flag and it changed thoroughly in automatedPreProcessing.py but not in common.py and there both flags are used, would be a good idea to make it consistent in order to avoid any confusion.

**Comment by hkjeldsberg** [comment]
> Line 70 of automatedPreProcessing.py, if not is_surface_capped(surface) and smoothing_method != "voronoi" does not work properly, it passes for both capped and clipped surfaces. Since is_surface_capped(surface) function in morphman surface_operation.py returens a tuple with 2 indices, and the first index is boolean, maybe that line can be modified as if is_surface_capped(surface)[0] and smoothing_method != "voronoi":

Agreed, this has been fixed

**Comment by hkjeldsberg** [comment]
@ehsannkh Do you think this is good to go? Will merge this when possible unless you have any other feedback

**Comment by ehsannkh** [comment]
> @ehsannkh Do you think this is good to go? Will merge this when possible unless you have any other feedback

@hkjeldsberg Not any feed back at the moment. Go ahead to merge it!

**Pull request merged**
