### PR TITLE
Update probe import path

### PR DESCRIPTION
**Pull request by hkjeldsberg**

### CODE REVIEW

**Comment by johannesring** [comment]
@hkjeldsberg - I see you have the same problems with CI as we had in VaSP. The fix for us was to downgrade the `expat` Conda package to 2.5.0.

**Comment by jorgensd** [comment]
> @hkjeldsberg - I see you have the same problems with CI as we had in VaSP. The fix for us was to downgrade the `expat` Conda package to 2.5.0.

Maybe we could ask @minrk to have a look and see if he can se what is going wrong?
If you know what package/function that relies on expat.

**Comment by johannesring** [comment]
It is vtk that depens on expat. There are some more info [here](https://discourse.paraview.org/t/i-cannot-read-a-vtp-file-i-could-open-yesterday-can-someone-try-to-open-it/13938/16) and [here](https://gitlab.archlinux.org/archlinux/packaging/packages/paraview/-/issues/4).

**Comment by hkjeldsberg** [comment]
Interesting. Will have to pin expat until they release a fix. @johannesring thanks a bunch for pointing this out.

**Comment by minrk** [comment]
From https://gitlab.kitware.com/vtk/vtk/-/issues/19258 it looks like conda-forge should pin libexpat 2.5 in vtk.

Done in https://github.com/conda-forge/vtk-feedstock/pull/321 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/682 . Once those land, conda-forge packages should install libexpat 2.5 with vtk instead of 2.6, but for now you should be able to apply the pin yourself.

**Pull request closed without merging**
