### PR TITLE
updated to allow 2D case

### PR DESCRIPTION
**Pull request by keiyamamo**
‘compute_flow_and_simulation_metrics.py’ can accept 2D case now.

### CODE REVIEW

**Comment by hkjeldsberg** [comment]
Looks good, nice work 👍 Will merge this when it has been tested

**Comment by hkjeldsberg** [comment]
@keiyamamo Did you manage to test this? 😊

**Comment by keiyamamo** [comment]
@hkjeldsberg It works with no problem but I have not validated against simple case yet :(

**Comment by hkjeldsberg** [comment]
> @hkjeldsberg It works with no problem but I have not validated against simple case yet :(

Okay, we can merge this for now and see if we find an appropriate case to validate against. Maybe Poiseuille flow would be a nice case to test this on.

**Comment by keiyamamo** [comment]
@hkjeldsberg  Thank you ! Yes, I think `LaminarChannel` from `Oasis` is probably the best test case.

**Pull request merged**
